### ISSUE TITLE
Assigning SID though OzStrips changes SID transition

### ISSUE THREAD

**Issue by zkgell** [maxrumsey/OzStrips#12]
Ozstrips seems to be adding the primary SID's waypoint into the flight plan when selecting the flights SID through OzStrips. This removes the correct transition waypoint from the strip.

**Comment by maxrumsey** [comment]
G'Day Zach, thanks for the issue!

I'm familiar with what you're referring to. I believe the same thing occurs in vatSys; when the runway field is entered into the vatSys strip, the SID is automatically entered. If you attempt to enter the SID in manually via the strip drop down menu, the same SID default termination point will be automatically inserted, (if memory serves correct). 

OzStrips is a bit over-eager when the SID is set; even if the currently assigned SID matches the chosen SID in OzStrips, the SID is still passed to vatSys. This results in said transition point being prepended with the default SID termination point. I've pushed commit b1f884255dbe97f8546e222d52beda65072bf7a1 which should prevent this, to the dev branch and will push to prod as soon as I can have a proper test.
