### ISSUE TITLE
"Non-Standard level"

### ISSUE THREAD

**Issue by BokBoy** [maxrumsey/OzStrips#19]
Hi!
Just popping in during my Sydney Tower Controlling session, 
I'm getting a "Possible Non-standard level" for a prop for a departure,
Normal level for that kind of flight is 030 but I'm getting that error;

Possible fix is to ignore any turboprops for altitude checking.
Sorry, No picture, Ground just hopped on and they don't use Ozstrips so stopped using it myself for this session.

Feel free to contact me on Discord (onlylordpotato or CID 1765892)
Thanks

**Comment by maxrumsey** [comment]
Closed after discussion over Discord
