### ISSUE TITLE
Permissions Implementation?

### ISSUE THREAD

**Issue by AntipodeYarns** [maxrumsey/OzStrips#26]
Not sure if this is an actual issue or not, but while logged in to VATSys as an observer, I accidentally discovered that I was able to move flight strips between control states. I couldn't see anything to suggest that this was having an impact on the live status of those flights within VatSys (still getting the hang of it all - observing for S1 controller exam qualification) but this seems like a potentially bad thing for an observer to be able to do.

Does the OzStrips system currently have any security controls that honour VATSys role constraints? If not, that seems like something that should be implemented as a high priority.

**Comment by maxrumsey** [comment]
There's client side authorisation checking that prevents synchronisation of client side state to the server, when the client is connected as an observer.

So while you were able to make changes, these were sandboxed to your client. (Although there's nothing but a note on the project website that tells the user this). It's not super robust, all permission checking is disabled when the plugin is running in vsstudio dev/debug mode, but given I think the plugin isn't a likely target for cyber attacks I reckon it's good enough. :)

**Comment by AntipodeYarns** [comment]
All good! Just wanted to make sure. As long as they're sandboxed to my own session, no dramas at all. 

Thanks for the update and quick response, Max!
